insert into "Bank" ("Name", "Code") values('Banco A.J.Renner S.A.','654');
insert into "Bank" ("Name", "Code") values('Banco ABC Brasil S.A.', '246');
insert into "Bank" ("Name", "Code") values('Banco Alfa S.A.','025');
insert into "Bank" ("Name", "Code") values('Banco Alvorada S.A.','641');
insert into "Bank" ("Name", "Code") values('Banco Arbi S.A.','213');
insert into "Bank" ("Name", "Code") values('Banco Azteca do Brasil S.A.','019');
insert into "Bank" ("Name", "Code") values('Banco Banerj S.A.','029');
insert into "Bank" ("Name", "Code") values('Banco Bankpar S.A.','000');
insert into "Bank" ("Name", "Code") values('Banco Barclays S.A.','740');
insert into "Bank" ("Name", "Code") values('Banco BBM S.A.','107');
insert into "Bank" ("Name", "Code") values('Banco Beg S.A.','031');
insert into "Bank" ("Name", "Code") values('Banco BGN S.A.','739');
insert into "Bank" ("Name", "Code") values('Banco BM&F de Serviços de Liquidação e Custódia S.A','096');
insert into "Bank" ("Name", "Code") values('Banco BMG S.A.','318');
insert into "Bank" ("Name", "Code") values('Banco BNP Paribas Brasil S.A.','752');
insert into "Bank" ("Name", "Code") values('Banco Boavista Interatlântico S.A.','248');
insert into "Bank" ("Name", "Code") values('Banco Bonsucesso S.A.','218');
insert into "Bank" ("Name", "Code") values('Banco Bracce S.A.','065');
insert into "Bank" ("Name", "Code") values('Banco Bradesco BBI S.A.','036');
insert into "Bank" ("Name", "Code") values('Banco Bradesco Cartões S.A.','204');
insert into "Bank" ("Name", "Code") values('Banco Bradesco Financiamentos S.A.','394');
insert into "Bank" ("Name", "Code") values('Banco Bradesco S.A.','237');
insert into "Bank" ("Name", "Code") values('Banco Brascan S.A.','225');
insert into "Bank" ("Name", "Code") values('Banco BRJ S.A.','M15');
insert into "Bank" ("Name", "Code") values('Banco BTG Pactual S.A.','208');
insert into "Bank" ("Name", "Code") values('Banco BVA S.A.','044');
insert into "Bank" ("Name", "Code") values('Banco Cacique S.A.','263');
insert into "Bank" ("Name", "Code") values('Banco Caixa Geral - Brasil S.A.','473');
insert into "Bank" ("Name", "Code") values('Banco Capital S.A.','412');
insert into "Bank" ("Name", "Code") values('Banco Cargill S.A.','040');
insert into "Bank" ("Name", "Code") values('Banco Citibank S.A.','745');
insert into "Bank" ("Name", "Code") values('Banco Citicard S.A.','M08');
insert into "Bank" ("Name", "Code") values('Banco Clássico S.A.','241');
insert into "Bank" ("Name", "Code") values('Banco CNH Capital S.A.','M19');
insert into "Bank" ("Name", "Code") values('Banco Comercial e de Investimento Sudameris S.A.','215');
insert into "Bank" ("Name", "Code") values('Banco Cooperativo do Brasil S.A. - BANCOOB','756');
insert into "Bank" ("Name", "Code") values('Banco Cooperativo Sicredi S.A.','748');
insert into "Bank" ("Name", "Code") values('Banco CR2 S.A.','075');
insert into "Bank" ("Name", "Code") values('Banco Credibel S.A.','721');
insert into "Bank" ("Name", "Code") values('Banco Credit Agricole Brasil S.A.','222');
insert into "Bank" ("Name", "Code") values('Banco Credit Suisse (Brasil) S.A.','505');
insert into "Bank" ("Name", "Code") values('Banco Cruzeiro do Sul S.A.','229');
insert into "Bank" ("Name", "Code") values('Banco Cédula S.A.','266');
insert into "Bank" ("Name", "Code") values('Banco da Amazônia S.A.','003');
insert into "Bank" ("Name", "Code") values('Banco da China Brasil S.A.','083-3');
insert into "Bank" ("Name", "Code") values('Banco Daimlerchrysler S.A.','M21');
insert into "Bank" ("Name", "Code") values('Banco Daycoval S.A.', '707');
insert into "Bank" ("Name", "Code") values('Banco de La Nacion Argentina','300');
insert into "Bank" ("Name", "Code") values('Banco de La Provincia de Buenos Aires','495');
insert into "Bank" ("Name", "Code") values('Banco de La Republica Oriental del Uruguay','494');
insert into "Bank" ("Name", "Code") values('Banco de Lage Landen Brasil S.A.','M06');
insert into "Bank" ("Name", "Code") values('Banco de Pernambuco S.A. - BANDEPE','024');
insert into "Bank" ("Name", "Code") values('Banco de Tokyo-Mitsubishi UFJ Brasil S.A.','456');
insert into "Bank" ("Name", "Code") values('Banco Dibens S.A.','214');
insert into "Bank" ("Name", "Code") values('Banco do Brasil S.A.', '001');
insert into "Bank" ("Name", "Code") values('Banco do Estado de Sergipe S.A.','047');
insert into "Bank" ("Name", "Code") values('Banco do Estado do Pará S.A.','037');
insert into "Bank" ("Name", "Code") values('Banco do Estado do Piauí S.A. - BEP','039');
insert into "Bank" ("Name", "Code") values('Banco do Estado do Rio Grande do Sul S.A.','041');
insert into "Bank" ("Name", "Code") values('Banco do Nordeste do Brasil S.A.','004');
insert into "Bank" ("Name", "Code") values('Banco Fator S.A.','265');
insert into "Bank" ("Name", "Code") values('Banco Fiat S.A.','M03');
insert into "Bank" ("Name", "Code") values('Banco Fibra S.A.','224');
insert into "Bank" ("Name", "Code") values('Banco Ficsa S.A.','626');
insert into "Bank" ("Name", "Code") values('Banco Ford S.A.','M18');
insert into "Bank" ("Name", "Code") values('Banco GE Capital S.A.','233');
insert into "Bank" ("Name", "Code") values('Banco Gerdau S.A.','734');
insert into "Bank" ("Name", "Code") values('Banco GMAC S.A.','M07');
insert into "Bank" ("Name", "Code") values('Banco Guanabara S.A.','612');
insert into "Bank" ("Name", "Code") values('Banco Honda S.A.','M22');
insert into "Bank" ("Name", "Code") values('Banco Ibi S.A. Banco Múltiplo','063');
insert into "Bank" ("Name", "Code") values('Banco IBM S.A.','M11');
insert into "Bank" ("Name", "Code") values('Banco Industrial do Brasil S.A.','604');
insert into "Bank" ("Name", "Code") values('Banco Industrial e Comercial S.A','320');
insert into "Bank" ("Name", "Code") values('Banco Indusval S.A.','653');
insert into "Bank" ("Name", "Code") values('Banco Intercap S.A.','630');
insert into "Bank" ("Name", "Code") values('Banco Intermedium S.A.','077-9');
insert into "Bank" ("Name", "Code") values('Banco Investcred Unibanco S.A.','249');
insert into "Bank" ("Name", "Code") values('Banco Itaucred Financiamentos S.A.','M09');
insert into "Bank" ("Name", "Code") values('Banco Itaú BBA S.A.','184');
insert into "Bank" ("Name", "Code") values('Banco ItaúBank S.A','479');
insert into "Bank" ("Name", "Code") values('Banco J. P. Morgan S.A.','376');
insert into "Bank" ("Name", "Code") values('Banco J. Safra S.A.','074');
insert into "Bank" ("Name", "Code") values('Banco John Deere S.A.','217');
insert into "Bank" ("Name", "Code") values('Banco KDB S.A.','076');
insert into "Bank" ("Name", "Code") values('Banco KEB do Brasil S.A.','757');
insert into "Bank" ("Name", "Code") values('Banco Luso Brasileiro S.A.','600');
insert into "Bank" ("Name", "Code") values('Banco Matone S.A.','212');
insert into "Bank" ("Name", "Code") values('Banco Maxinvest S.A.','M12');
insert into "Bank" ("Name", "Code") values('Banco Mercantil do Brasil S.A.','389');
insert into "Bank" ("Name", "Code") values('Banco Modal S.A.','746');
insert into "Bank" ("Name", "Code") values('Banco Moneo S.A.','M10');
insert into "Bank" ("Name", "Code") values('Banco Morada S.A.','738');
insert into "Bank" ("Name", "Code") values('Banco Morgan Stanley S.A.','066');
insert into "Bank" ("Name", "Code") values('Banco Máxima S.A.','243');
insert into "Bank" ("Name", "Code") values('Banco Opportunity S.A.','045');
insert into "Bank" ("Name", "Code") values('Banco Ourinvest S.A.','M17');
insert into "Bank" ("Name", "Code") values('Banco PaNamericano S.A.','623');
insert into "Bank" ("Name", "Code") values('Banco Paulista S.A.','611');
insert into "Bank" ("Name", "Code") values('Banco Pecúnia S.A.','613');
insert into "Bank" ("Name", "Code") values('Banco Petra S.A.','094-2');
insert into "Bank" ("Name", "Code") values('Banco Pine S.A.','643');
insert into "Bank" ("Name", "Code") values('Banco Porto Seguro S.A.','724');
insert into "Bank" ("Name", "Code") values('Banco Pottencial S.A.','735');
insert into "Bank" ("Name", "Code") values('Banco Prosper S.A.','638');
insert into "Bank" ("Name", "Code") values('Banco PSA Finance Brasil S.A.','M24');
insert into "Bank" ("Name", "Code") values('Banco Rabobank International Brasil S.A.','747');
insert into "Bank" ("Name", "Code") values('Banco Randon S.A.','088-4');
insert into "Bank" ("Name", "Code") values('Banco Real S.A.','356');
insert into "Bank" ("Name", "Code") values('Banco Rendimento S.A.','633');
insert into "Bank" ("Name", "Code") values('Banco Ribeirão Preto S.A.','741');
insert into "Bank" ("Name", "Code") values('Banco Rodobens S.A.','M16');
insert into "Bank" ("Name", "Code") values('Banco Rural Mais S.A.','072');
insert into "Bank" ("Name", "Code") values('Banco Rural S.A.','453');
insert into "Bank" ("Name", "Code") values('Banco Safra S.A.','422');
insert into "Bank" ("Name", "Code") values('Banco Santander (Brasil) S.A.','033');
insert into "Bank" ("Name", "Code") values('Banco Schahin S.A.','250');
insert into "Bank" ("Name", "Code") values('Banco Semear S.A.','743');
insert into "Bank" ("Name", "Code") values('Banco Simples S.A.','749');
insert into "Bank" ("Name", "Code") values('Banco Société Générale Brasil S.A.','366');
insert into "Bank" ("Name", "Code") values('Banco Sofisa S.A.','637');
insert into "Bank" ("Name", "Code") values('Banco Standard de Investimentos S.A.','012');
insert into "Bank" ("Name", "Code") values('Banco Sumitomo Mitsui Brasileiro S.A.','464');
insert into "Bank" ("Name", "Code") values('Banco Topázio S.A.','082-5');
insert into "Bank" ("Name", "Code") values('Banco Toyota do Brasil S.A.','M20');
insert into "Bank" ("Name", "Code") values('Banco Tricury S.A.','M13');
insert into "Bank" ("Name", "Code") values('Banco Triângulo S.A.','634');
insert into "Bank" ("Name", "Code") values('Banco Volkswagen S.A.','M14');
insert into "Bank" ("Name", "Code") values('Banco Volvo (Brasil) S.A.','M23');
insert into "Bank" ("Name", "Code") values('Banco Votorantim S.A.','655');
insert into "Bank" ("Name", "Code") values('Banco VR S.A.','610');
insert into "Bank" ("Name", "Code") values('Banco WestLB do Brasil S.A.','370');
insert into "Bank" ("Name", "Code") values('BANESTES S.A. Banco do Estado do Espírito Santo','021');
insert into "Bank" ("Name", "Code") values('Banif-Banco Internacional do Funchal (Brasil)S.A.','719');
insert into "Bank" ("Name", "Code") values('Bank of America Merrill Lynch Banco Múltiplo S.A.','755');
insert into "Bank" ("Name", "Code") values('BankBoston N.A.','744');
insert into "Bank" ("Name", "Code") values('BB Banco Popular do Brasil S.A.','073');
insert into "Bank" ("Name", "Code") values('BES Investimento do Brasil S.A.-Banco de Investimento','078');
insert into "Bank" ("Name", "Code") values('BPN Brasil Banco Múltiplo S.A.','069');
insert into "Bank" ("Name", "Code") values('BRB - Banco de Brasília S.A.','070');
insert into "Bank" ("Name", "Code") values('Brickell S.A. Crédito, financiamento e Investimento','092-2');
insert into "Bank" ("Name", "Code") values('Caixa Econômica Federal','104');
insert into "Bank" ("Name", "Code") values('Citibank N.A.','477');
insert into "Bank" ("Name", "Code") values('Concórdia Banco S.A.','081-7');
insert into "Bank" ("Name", "Code") values('Cooperativa Central de Crédito Noroeste Brasileiro Ltda.','097-3');
insert into "Bank" ("Name", "Code") values('Cooperativa Central de Crédito Urbano-CECRED','085-x');
insert into "Bank" ("Name", "Code") values('Cooperativa Central de Economia e Credito Mutuo das Unicreds','099-x');
insert into "Bank" ("Name", "Code") values('Cooperativa Central de Economia e Crédito Mutuo das Unicreds','090-2');
insert into "Bank" ("Name", "Code") values('Cooperativa de Crédito Rural da Região de Mogiana','089-2');
insert into "Bank" ("Name", "Code") values('Cooperativa Unicred Central Santa Catarina','087-6');
insert into "Bank" ("Name", "Code") values('Credicorol Cooperativa de Crédito Rural','098-1');
insert into "Bank" ("Name", "Code") values('Deutsche Bank S.A. - Banco Alemão','487');
insert into "Bank" ("Name", "Code") values('Dresdner Bank Brasil S.A. - Banco Múltiplo','751');
insert into "Bank" ("Name", "Code") values('Goldman Sachs do Brasil Banco Múltiplo S.A.','064');
insert into "Bank" ("Name", "Code") values('Hipercard Banco Múltiplo S.A.','062');
insert into "Bank" ("Name", "Code") values('HSBC Bank Brasil S.A. - Banco Múltiplo','399');
insert into "Bank" ("Name", "Code") values('HSBC Finance (Brasil) S.A. - Banco Múltiplo','168');
insert into "Bank" ("Name", "Code") values('ING Bank N.V.','492');
insert into "Bank" ("Name", "Code") values('Itaú Unibanco Holding S.A.','652');
insert into "Bank" ("Name", "Code") values('Itaú Unibanco S.A.','341');
insert into "Bank" ("Name", "Code") values('JBS Banco S.A.','079');
insert into "Bank" ("Name", "Code") values('JPMorgan Chase Bank','488');
insert into "Bank" ("Name", "Code") values('Natixis Brasil S.A. Banco Múltiplo	','014');
insert into "Bank" ("Name", "Code") values('NBC Bank Brasil S.A. - Banco Múltiplo','753');
insert into "Bank" ("Name", "Code") values('OBOE Crédito Financiamento e Investimento S.A.','086-8');
insert into "Bank" ("Name", "Code") values('Paraná Banco S.A.','254');
insert into "Bank" ("Name", "Code") values('UNIBANCO - União de Bancos Brasileiros S.A.','409');
insert into "Bank" ("Name", "Code") values('Unicard Banco Múltiplo S.A.','230');
insert into "Bank" ("Name", "Code") values('Unicred Central do Rio Grande do Sul','091-4');
insert into "Bank" ("Name", "Code") values('Unicred Norte do Paraná','084');

