INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (1, 'Acre', 'AC');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (2, 'Alagoas', 'AL');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (3, 'Amazonas', 'AM');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (4, 'Amapá', 'AP');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (5, 'Bahia', 'BA');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (6, 'Ceará', 'CE');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (7, 'Distrito Federal', 'DF');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (8, 'Espirito Santo', 'ES');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (9, 'Goiás', 'GO');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (10, 'Maranhão', 'MA');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (11, 'Minas Gerais', 'MG');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (12, 'Mato Grosso do Sul', 'MS');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (13, 'Mato Grosso', 'MT');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (14, 'Pará', 'PA');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (15, 'Paraíba', 'PB');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (16, 'Pernambuco', 'PE');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (17, 'Piauí', 'PI');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (18, 'Paraná', 'PR');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (19, 'Rio de Janeiro', 'RJ');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (20, 'Rio Grande do Norte', 'RN');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (21, 'Rondônia', 'RO');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (22, 'Roraima', 'RR');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (23, 'Rio Grande do Sul', 'RS');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (24, 'Santa Catarina', 'SC');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (25, 'Sergipe', 'SE');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (26, 'São Paulo', 'SP');
INSERT INTO "State" ("Id", "Name", "Abbrev") VALUES (27, 'Tocantins', 'TO');